### ISSUE TITLE
Realistic World doesn´t starts

### ISSUE THREAD

**Issue by srfabric** [SourceWriters/LoginPlus#33]
```
[22:34:19 ERROR]: Could not pass event PluginEnableEvent to Realistic_World v4.39.5
java.lang.NullPointerException: Cannot invoke "net.sourcewriters.spigot.rwg.legacy.api.compatibility.CompatibilityAddon.enable(net.sourcewriters.spigot.rwg.legacy.api.RealisticWorldGenerator)" because "this.orthopyramid" is null
        at net.sourcewriters.spigot.rwg.legacy.helloThereHowAreYouDoing.albuminise.filibegs(SourceFile:89) ~[RealisticWorldGenerator-4.39.5.jar:?]
        at net.sourcewriters.spigot.rwg.legacy.helloThereHowAreYouDoing.chattier.filibegs(SourceFile:203) ~[RealisticWorldGenerator-4.39.5.jar:?]
        at net.sourcewriters.spigot.rwg.legacy.helloThereHowAreYouDoing.chattier.oudenodont(SourceFile:185) ~[RealisticWorldGenerator-4.39.5.jar:?]
        at net.sourcewriters.spigot.rwg.legacy.helloThereHowAreYouDoing.chattier.filibegs(SourceFile:221) ~[RealisticWorldGenerator-4.39.5.jar:?]
        at net.sourcewriters.spigot.rwg.legacy.helloThereHowAreYouDoing.chattier.onEnable(SourceFile:226) ~[RealisticWorldGenerator-4.39.5.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Purpur-1428]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:381) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:736) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:353) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1233) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1428]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]```

**Comment by YellowPhoenix18** [comment]
Please follow our guidlines for issues and add a full log and not just a snippet. We will close this issue, as it is not matching our guidlines
