### ISSUE TITLE
1.19.3 seems to break

### ISSUE THREAD

**Issue by Soapy7261** [SourceWriters/LoginPlus#38]
I am on the latest version, trying to connect to my server using waterfall but it seems to break
Server jar: Pufferfish (fork of paper) 1.19.3
(I tested on paper and the same problem happens)
Network jar: Waterfall
Pufferfish error:
```10.02 19:50:17 [Server] Startup[19:50:17 [INFO]]: [STDOUT] [net.sourcewriters.minecraft.vcompat.VersionCompatProvider] Initializing vCompat on with 'v1_19_R2' core on '1.19.3'!
10.02 19:50:17 [Server] Startup[19:50:17 [WARN]]: [LoginPlus] Task #3 for LoginPlus v3.2.1 generated an exception
10.02 19:50:17 [Server] [INFO] java.lang.IllegalStateException: Failed to initialize vCompat implementation
10.02 19:50:17 [Server] [INFO] at net.sourcewriters.minecraft.vcompat.VersionCompatProvider.get(VersionCompatProvider.java:31) ~[vCompat.jar:?]
10.02 19:50:17 [Server] [INFO] at com.syntaxphoenix.loginplus.utils.PlayerHelper.sendTitle(PlayerHelper.java:13) ~[LoginPlus-3.2.1.jar:?]
10.02 19:50:17 [Server] [INFO] at com.syntaxphoenix.loginplus.utils.login.LoginCallback.handleLogin(LoginCallback.java:70) ~[LoginPlus-3.2.1.jar:?]
10.02 19:50:17 [Server] [INFO] at com.syntaxphoenix.loginplus.utils.login.LoginManager.callbackUser(LoginManager.java:32) ~[LoginPlus-3.2.1.jar:?]
10.02 19:50:17 [Server] [INFO] at com.syntaxphoenix.loginplus.accounts.manager.AccountManager.setLocalAccount(AccountManager.java:36) ~[LoginPlus-3.2.1.jar:?]
10.02 19:50:17 [Server] [INFO] at com.syntaxphoenix.loginplus.accounts.tasks.SyncSetLocalAccount.run(SyncSetLocalAccount.java:22) ~[LoginPlus-3.2.1.jar:?]
10.02 19:50:17 [Server] [INFO] at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.19.3.jar:git-Pufferfish-58]
10.02 19:50:17 [Server] [INFO] at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[pufferfish-1.19.3.jar:git-Pufferfish-58]
10.02 19:50:17 [Server] [INFO] at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1475) ~[pufferfish-1.19.3.jar:git-Pufferfish-58]
10.02 19:50:17 [Server] [INFO] at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:443) ~[pufferfish-1.19.3.jar:git-Pufferfish-58]
10.02 19:50:17 [Server] [INFO] at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1399) ~[pufferfish-1.19.3.jar:git-Pufferfish-58]
10.02 19:50:17 [Server] [INFO] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[pufferfish-1.19.3.jar:git-Pufferfish-58]
10.02 19:50:17 [Server] [INFO] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[pufferfish-1.19.3.jar:git-Pufferfish-58]
10.02 19:50:17 [Server] [INFO] at java.lang.Thread.run(Thread.java:831) ~[?:?]
10.02 19:50:17 [Server] [INFO] Caused by: java.lang.IllegalStateException: Can't initialize VersionControl
10.02 19:50:17 [Server] [INFO] at net.sourcewriters.minecraft.vcompat.VersionCompat.initControl(VersionCompat.java:36) ~[vCompat.jar:?]
10.02 19:50:19 [Server] [INFO] at net.sourcewriters.minecraft.vcompat.VersionCompat.init(VersionCompat.java:22) ~[vCompat.jar:?]
10.02 19:50:19 [Server] [INFO] at net.sourcewriters.minecraft.vcompat.VersionCompatProvider.get(VersionCompatProvider.java:29) ~[vCompat.jar:?]
10.02 19:50:19 [Server] [INFO] ... 13 more
```
Paper error:
```
10.02 19:53:41 [Server] [INFO] [STDOUT] [net.sourcewriters.minecraft.vcompat.VersionCompatProvider] Initializing vCompat on with 'v1_19_R2' core on '1.19.3'!
10.02 19:53:41 [Server] [WARN] [LoginPlus] Task #3 for LoginPlus v3.2.1 generated an exception
10.02 19:53:41 [Server] [INFO] java.lang.IllegalStateException: Failed to initialize vCompat implementation
10.02 19:53:41 [Server] [INFO] at net.sourcewriters.minecraft.vcompat.VersionCompatProvider.get(VersionCompatProvider.java:31) ~[vCompat.jar:?]
10.02 19:53:41 [Server] [INFO] at com.syntaxphoenix.loginplus.utils.PlayerHelper.sendTitle(PlayerHelper.java:13) ~[LoginPlus-3.2.1.jar:?]
10.02 19:53:41 [Server] [INFO] at com.syntaxphoenix.loginplus.utils.login.LoginCallback.handleLogin(LoginCallback.java:70) ~[LoginPlus-3.2.1.jar:?]
10.02 19:53:41 [Server] [INFO] at com.syntaxphoenix.loginplus.utils.login.LoginManager.callbackUser(LoginManager.java:32) ~[LoginPlus-3.2.1.jar:?]
10.02 19:53:41 [Server] [INFO] at com.syntaxphoenix.loginplus.accounts.manager.AccountManager.setLocalAccount(AccountManager.java:36) ~[LoginPlus-3.2.1.jar:?]
10.02 19:53:41 [Server] [INFO] at com.syntaxphoenix.loginplus.accounts.tasks.SyncSetLocalAccount.run(SyncSetLocalAccount.java:22) ~[LoginPlus-3.2.1.jar:?]
10.02 19:53:41 [Server] [INFO] at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-"5eca964"]
10.02 19:53:41 [Server] [INFO] at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.3.jar:git-Paper-"5eca964"]
10.02 19:53:41 [Server] [INFO] at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.3.jar:git-Paper-"5eca964"]
10.02 19:53:41 [Server] [INFO] at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:440) ~[paper-1.19.3.jar:git-Paper-"5eca964"]
10.02 19:53:41 [Server] [INFO] at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-"5eca964"]
10.02 19:53:41 [Server] [INFO] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-"5eca964"]
10.02 19:53:41 [Server] [INFO] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-"5eca964"]
10.02 19:53:41 [Server] [INFO] at java.lang.Thread.run(Thread.java:831) ~[?:?]
10.02 19:53:41 [Server] [INFO] Caused by: java.lang.IllegalStateException: Can't initialize VersionControl
10.02 19:53:41 [Server] [INFO] at net.sourcewriters.minecraft.vcompat.VersionCompat.initControl(VersionCompat.java:36) ~[vCompat.jar:?]
10.02 19:53:41 [Server] [INFO] at net.sourcewriters.minecraft.vcompat.VersionCompat.init(VersionCompat.java:22) ~[vCompat.jar:?]
10.02 19:53:41 [Server] [INFO] at net.sourcewriters.minecraft.vcompat.VersionCompatProvider.get(VersionCompatProvider.java:29) ~[vCompat.jar:?]
10.02 19:53:41 [Server] [INFO] ... 13 more
```
Seems the error is caused by vCompat not supporting 1.19.3 or something

**Comment by PSYCHEER** [comment]
Purpur 1.19.3 same
Looks like an error by version of minecraft server rather than a fork...

**Comment by YellowPhoenix18** [comment]
We have this in mind, as some projects have higher priority the update might take a while. If you have knowledge, feel free to make a pull request and contribute to the project. In this way we can push an update faster.

**Comment by YellowPhoenix18** [comment]
Seems to apply to all 1.19-Versions, as of #34

**Comment by Lauriichan** [comment]
I don't think this can be considered a LP issue, probably more a [vCompat ](https://github.com/SourceWriters/vCompat) issue here

**Comment by Lauriichan** [comment]
Well I guess the reason is that vCompat doesn't support 1_19_R2 (which is only 1.19.3 so far) yet

**Comment by Lauriichan** [comment]
> Seems to apply to all 1.19-Versions, as of #34

Probably not, 1_19_R1 (1.19 - 1.19.2) is supported by vCompat
